### ISSUE TITLE
Wallpaper and Styles app crashes

### ISSUE THREAD

**Issue by anilbeesetti** [zeelog/OTA#62]
wallpaper and styles app crashes with this exception

```FATAL EXCEPTION: main
Process: com.android.wallpaper, PID: 18665
java.lang.NullPointerException
	at com.android.customization.model.color.ColorSectionController$maybeLoadColors$1.invokeSuspend(ColorSectionController.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:457)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.android.customization.model.color.ColorSectionController.maybeLoadColors(ColorSectionController.kt:213)
	at com.android.customization.model.color.ColorSectionController.access$maybeLoadColors(ColorSectionController.kt:32)
	at com.android.customization.model.color.ColorSectionController$createView$2.onChanged(ColorSectionController.kt:117)
	at com.android.customization.model.color.ColorSectionController$createView$2.onChanged(ColorSectionController.kt:114)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at com.android.wallpaper.model.WallpaperSectionController.onLockWallpaperColorsChanged(WallpaperSectionController.java:429)
	at com.android.wallpaper.model.WallpaperSectionController.lambda$refreshCurrentWallpapers$6$WallpaperSectionController(WallpaperSectionController.java:364)
	at com.android.wallpaper.model.WallpaperSectionController$$ExternalSyntheticLambda5.onWallpaperInfoCreated(Unknown Source:2)
	at com.android.wallpaper.module.DefaultCurrentWallpaperInfoFactory.lambda$createCurrentWallpaperInfos$0$DefaultCurrentWallpaperInfoFactory(DefaultCurrentWallpaperInfoFactory.java:100)
	at com.android.wallpaper.module.DefaultCurrentWallpaperInfoFactory$$ExternalSyntheticLambda0.onRefreshed(Unknown Source:4)
	at com.android.wallpaper.module.DefaultWallpaperRefresher$GetWallpaperMetadataAsyncTask.onPostExecute(DefaultWallpaperRefresher.java:153)
	at com.android.wallpaper.module.DefaultWallpaperRefresher$GetWallpaperMetadataAsyncTask.onPostExecute(DefaultWallpaperRefresher.java:78)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7877)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)```

**Comment by zeelog** [comment]
please try with latest release (11th May)

**Comment by anilbeesetti** [comment]
It's working fine now. Thanks man, Great work
